# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v3
      with:
        python-version: "3.14"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build Flet
      run: flet build ipa --yes
      
    - name: Convert to IPA
      run: |
        ls build/ipa
        mv build/ipa/beluga.xcarchive/Products/Applications build/ipa/beluga.xcarchive/Products/Payload
        cd build/ipa/beluga.xcarchive/Products/
        zip -r beluga.zip Payload
        mv beluga.zip beluga.ipa
        ls
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        path: beluga.ipa
  
      
